language: ruby
rvm:
 - 2.2.5

before_script:
  - mysql -e 'create database IF NOT EXISTS vegj_test;'

services:
  # http://stackoverflow.com/questions/9321153/rails-database-setup-on-travis-ci
  # https://docs.travis-ci.com/user/database-setup/#MySQL
  - mysql
